Added Lab 3 and README file
NoFaceBoy/Lab-3 pull request #1
Opened 2021-10-27 16:57 UTC by NoFaceBoy

The code from the third lab finds your lucky number. First of all, you need to enter N number (max 10 numbers), after that choose your K key (1-9). Code forms new number M from every K symbol. When the number is formed it should be multiple of three, only then it is considered lucky. Program prints down that number and tells you, YES or NO depending on if the number is lucky or not.
Example:
N = 123456789
K = 3
M = 369485271
YES

2021-10-28 09:01 UTC, RybOlya requested changes

2021-10-28 09:01 UTC, RybOlya commented on lab3.c
> +	scanf_s("%i", &k);
The function executes too many functions at once, i recommend getting number from user in main and pass it to function

2021-10-28 09:01 UTC, RybOlya commented on lab3.c
> +	long n = 0;
Is it necessary to use long?

2021-10-28 09:01 UTC, RybOlya commented on lab3.c
> +	int num = 0;
Your n and num variables are similar, rename one

2021-10-28 09:01 UTC, RybOlya commented on lab3.c
> +	int z = 0;
In for cycles, variable i is more used

2021-10-28 09:01 UTC, RybOlya commented on lab3.c
> +	if (sum % 3 == 0)
I recommend returning value from function to main print  out YES or NO according to the return value in main

2021-10-28 09:01 UTC, RybOlya commented on lab3.c
> +		int f = k;
What is the meaning of f variable?

2021-10-28 09:01 UTC, RybOlya commented on lab3.c
> +		if (ptrA[i] != 10) {
Avoid negative conditionals

2021-10-28 09:01 UTC, RybOlya commented on lab3.c
> +#include <stdio.h>
Add comments to your code

2021-10-31 22:41 UTC, NoFaceBoy commented on lab3.c
> +	scanf_s("%i", &k);
Fixed

2021-10-31 22:42 UTC, NoFaceBoy commented on lab3.c
> +	long n = 0;
Changed

2021-10-31 22:42 UTC, NoFaceBoy commented on lab3.c
> +	int num = 0;
Renamed

2021-10-31 22:42 UTC, NoFaceBoy commented on lab3.c
> +	int z = 0;
Changed

2021-10-31 22:42 UTC, NoFaceBoy commented on lab3.c
> +	if (sum % 3 == 0)
Fixed

2021-10-31 22:43 UTC, NoFaceBoy commented on lab3.c
> +		int f = k;
k variable is used to save the key value, f variable used to move through available numbers, changed the names for them

2021-10-31 22:44 UTC, NoFaceBoy commented on lab3.c
> +		if (ptrA[i] != 10) {
I marked used numbers as 10, so I won't get them to the new number again, that's why it is used like that

2021-10-31 22:45 UTC, NoFaceBoy commented on lab3.c
> +#include <stdio.h>
added

2021-11-01 06:26 UTC, RybOlya approved these changes

2021-12-20 09:27 UTC, zveres-ss requested changes

2021-12-20 09:27 UTC, zveres-ss commented on lab3.c
> +	int k;
do not use single-letter variable names

2021-12-20 09:27 UTC, zveres-ss commented on lab3.c
> +	int reversed[10];
make 10 as constant or even better to use #define EXPLAINABLE_NAME 10

2022-09-29 20:38 UTC, merged